
POST http://localhost:8080/api/pitometer/dynatrace
Content-Type: application/json

{
  "monspec": {
    "spec_version": "1.0",
    "indicators": [
      {
        "id": "P90_ResponseTime_Frontend",
        "source": "Dynatrace",
        "query": {
          "timeseriesId": "com.dynatrace.builtin:service.responsetime",
          "aggregation": "p90",
          "tags": [
            "dt-kube-demo-environment:production",
            "dt-kube-demo-service:front-end"
          ]
        },
        "grading": {
          "type": "Threshold",
          "thresholds": {
            "upperSevere": 4000000,
            "upperWarning": 2000000,
            "lowerWarning ": 0,
            "lowerSevere": 0
          },
          "metricScore": 80
        }
      },
      {
        "id": "AVG_ResponseTime_Frontend",
        "source": "Dynatrace",
        "query": {
          "timeseriesId": "com.dynatrace.builtin:service.responsetime",
          "aggregation": "avg",
          "tags": [
            "dt-kube-demo-environment:production",
            "dt-kube-demo-service:front-end"
          ]
        },
        "grading": {
          "type": "Threshold",
          "thresholds": {
            "upperSevere": 4000000,
            "upperWarning": 2000000,
            "lowerWarning ": 0,
            "lowerSevere": 0
          },
          "metricScore": 80
        }
      },
      {
        "id": "P90_ResponseTime_Backend",
        "source": "Dynatrace",
        "query": {
          "timeseriesId": "com.dynatrace.builtin:service.responsetime",
          "aggregation": "p90",
          "tags": [
            "dt-kube-demo-environment:production",
            "dt-kube-demo-service:catalog"
          ]
        },
        "grading": {
          "type": "Threshold",
          "thresholds": {
            "upperSevere": 1000000,
            "upperWarning": 500000,
            "lowerWarning ": 0,
            "lowerSevere": 0
          },
          "metricScore": 20
        }
      },
      {
        "id": "AVG_ResponseTime_Backend",
        "source": "Dynatrace",
        "query": {
          "timeseriesId": "com.dynatrace.builtin:service.responsetime",
          "aggregation": "avg",
          "tags": [
            "dt-kube-demo-environment:production",
            "dt-kube-demo-service:catalog"
          ]
        },
        "grading": {
          "type": "Threshold",
          "thresholds": {
            "upperSevere": 1000000,
            "upperWarning": 500000,
            "lowerWarning ": 0,
            "lowerSevere": 0
          },
          "metricScore": 20
        }
      }
    ],
    "objectives": {
      "pass": 90,
      "warning": 75
    }
  }
}
###

POST https://pitometer.azurewebsites.net/api/pitometer?code=ryqBx5JWWRfyPtgvCHd84edO7aul317665Qza0SGca/HZRp4mOuVsg==
Content-Type: application/json

{
  "monspec": {
    "spec_version": "1.0",
    "indicators": [
      {
        "id": "P90_ResponseTime_Frontend",
        "source": "Dynatrace",
        "query": {
          "timeseriesId": "com.dynatrace.builtin:service.responsetime",
          "aggregation": "p90",
          "tags": [
            "dt-kube-demo-environment:production",
            "dt-kube-demo-service:front-end"
          ]
        },
        "grading": {
          "type": "Threshold",
          "thresholds": {
            "upperSevere": 4000000,
            "upperWarning": 2000000,
            "lowerWarning ": 0,
            "lowerSevere": 0
          },
          "metricScore": 80
        }
      },
      {
        "id": "AVG_ResponseTime_Frontend",
        "source": "Dynatrace",
        "query": {
          "timeseriesId": "com.dynatrace.builtin:service.responsetime",
          "aggregation": "avg",
          "tags": [
            "dt-kube-demo-environment:production",
            "dt-kube-demo-service:front-end"
          ]
        },
        "grading": {
          "type": "Threshold",
          "thresholds": {
            "upperSevere": 4000000,
            "upperWarning": 2000000,
            "lowerWarning ": 0,
            "lowerSevere": 0
          },
          "metricScore": 80
        }
      },
      {
        "id": "P90_ResponseTime_Backend",
        "source": "Dynatrace",
        "query": {
          "timeseriesId": "com.dynatrace.builtin:service.responsetime",
          "aggregation": "p90",
          "tags": [
            "dt-kube-demo-environment:production",
            "dt-kube-demo-service:catalog"
          ]
        },
        "grading": {
          "type": "Threshold",
          "thresholds": {
            "upperSevere": 1000000,
            "upperWarning": 500000,
            "lowerWarning ": 0,
            "lowerSevere": 0
          },
          "metricScore": 20
        }
      },
      {
        "id": "AVG_ResponseTime_Backend",
        "source": "Dynatrace",
        "query": {
          "timeseriesId": "com.dynatrace.builtin:service.responsetime",
          "aggregation": "avg",
          "tags": [
            "dt-kube-demo-environment:production",
            "dt-kube-demo-service:catalog"
          ]
        },
        "grading": {
          "type": "Threshold",
          "thresholds": {
            "upperSevere": 1000000,
            "upperWarning": 500000,
            "lowerWarning ": 0,
            "lowerSevere": 0
          },
          "metricScore": 20
        }
      }
    ],
    "objectives": {
      "pass": 90,
      "warning": 75
    }
  }
}

###
POST https://kspitometer.azurewebsites.net
Content-Type: application/json

{
  "name":"john"
}

###
http://webapppitometer.azurewebsites.net/
